collections:
  people:
    output: true
  research:
    output: true
  filters:
    output: true
    permalink: /publications/:name
  news:
    output: true
  courses:
    output: false
  projects:
    output: true

theme: rug-ds-theme

sass:
  style: compressed
  load_paths:
    - _sass
    # - vendor/bundle/**/bootstrap-5.3.3/assets/stylesheets
  silence_deprecations: [
    "mixed-decls",
    "color-functions",
    "global-builtin",
    "import",
  ]

exclude:
  - fetch_bibtex.py
  - README.md
  - vendor*

plugins:
  - jekyll-scholar

scholar:
  type: apa
  bibliography: /*.bib
  sort_by: year, type, month
  order: descending, descending, descending
  type_order: [book, phdthesis, proceedings, booklet, inbook, article, incollection, inproceedings, techreport, manual, masterthesis, unpublished, misc]
  bibtex_filters: latex
  bibliography_template: bib_entry
