name: Weekly Site Update

on:
  schedule:
    - cron: '0 9 * * 1'   # every Monday at 09:00 UTC
  workflow_dispatch:       # optional manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}   # <--- add this line

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run update script
        run: |
          python fetch_bibtex.py


      - name: Commit and push changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git status
          git diff --cached --stat
          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
          else
            git commit -m "📚 bib update - $(date -u '+%Y-%m-%d %H:%M:%S')"
            git push origin main
          fi
